// QuantumShield Hub — API contract (v1).
//
// gRPC services and message contracts for the QuantumShield telemetry
// control plane:
//
//   - TelemetryIngestionService: bidirectional streaming ingestion of
//     edge telemetry with per-payload ML-DSA (Dilithium, FIPS 204)
//     signatures.
//   - DeviceAuthService: device identity lifecycle, PQC public-key lookup
//     and status checks.
//
// Wire rules (AGENTS.md §3, gRPC & Protocol Buffers):
//   - Never renumber, reorder or change the type of an existing field.
//   - New functionality only appends new field numbers.
//
// Transport: hybrid PQC mTLS (TLS 1.3, X25519 + ML-KEM-768). Payloads are
// signed by the edge node with ML-DSA and verified by the Ingestion
// Service before acceptance.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/v1/telemetry.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ML-DSA (Dilithium, FIPS 204) parameter set used for a signature.
type SignatureAlgorithm int32

const (
	SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED SignatureAlgorithm = 0
	SignatureAlgorithm_ML_DSA_44                       SignatureAlgorithm = 1
	SignatureAlgorithm_ML_DSA_65                       SignatureAlgorithm = 2
	SignatureAlgorithm_ML_DSA_87                       SignatureAlgorithm = 3
)

// Enum value maps for SignatureAlgorithm.
var (
	SignatureAlgorithm_name = map[int32]string{
		0: "SIGNATURE_ALGORITHM_UNSPECIFIED",
		1: "ML_DSA_44",
		2: "ML_DSA_65",
		3: "ML_DSA_87",
	}
	SignatureAlgorithm_value = map[string]int32{
		"SIGNATURE_ALGORITHM_UNSPECIFIED": 0,
		"ML_DSA_44":                       1,
		"ML_DSA_65":                       2,
		"ML_DSA_87":                       3,
	}
)

func (x SignatureAlgorithm) Enum() *SignatureAlgorithm {
	p := new(SignatureAlgorithm)
	*p = x
	return p
}

func (x SignatureAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (SignatureAlgorithm) Type() protoreflect.EnumType {
	return &file_api_v1_telemetry_proto_enumTypes[0]
}

func (x SignatureAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureAlgorithm.Descriptor instead.
func (SignatureAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// Lifecycle state of a registered device.
type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_ACTIVE      DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_SUSPENDED   DeviceStatus = 2
	DeviceStatus_DEVICE_STATUS_REVOKED     DeviceStatus = 3
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNSPECIFIED",
		1: "DEVICE_STATUS_ACTIVE",
		2: "DEVICE_STATUS_SUSPENDED",
		3: "DEVICE_STATUS_REVOKED",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNSPECIFIED": 0,
		"DEVICE_STATUS_ACTIVE":      1,
		"DEVICE_STATUS_SUSPENDED":   2,
		"DEVICE_STATUS_REVOKED":     3,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_telemetry_proto_enumTypes[1].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_api_v1_telemetry_proto_enumTypes[1]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

// Per-event ingestion result returned to the edge node.
type IngestStatus int32

const (
	IngestStatus_INGEST_STATUS_UNSPECIFIED        IngestStatus = 0
	IngestStatus_INGEST_STATUS_ACCEPTED           IngestStatus = 1
	IngestStatus_INGEST_STATUS_REJECTED_SIGNATURE IngestStatus = 2
	IngestStatus_INGEST_STATUS_REJECTED_DEVICE    IngestStatus = 3
	IngestStatus_INGEST_STATUS_THROTTLED          IngestStatus = 4
)

// Enum value maps for IngestStatus.
var (
	IngestStatus_name = map[int32]string{
		0: "INGEST_STATUS_UNSPECIFIED",
		1: "INGEST_STATUS_ACCEPTED",
		2: "INGEST_STATUS_REJECTED_SIGNATURE",
		3: "INGEST_STATUS_REJECTED_DEVICE",
		4: "INGEST_STATUS_THROTTLED",
	}
	IngestStatus_value = map[string]int32{
		"INGEST_STATUS_UNSPECIFIED":        0,
		"INGEST_STATUS_ACCEPTED":           1,
		"INGEST_STATUS_REJECTED_SIGNATURE": 2,
		"INGEST_STATUS_REJECTED_DEVICE":    3,
		"INGEST_STATUS_THROTTLED":          4,
	}
)

func (x IngestStatus) Enum() *IngestStatus {
	p := new(IngestStatus)
	*p = x
	return p
}

func (x IngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_telemetry_proto_enumTypes[2].Descriptor()
}

func (IngestStatus) Type() protoreflect.EnumType {
	return &file_api_v1_telemetry_proto_enumTypes[2]
}

func (x IngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestStatus.Descriptor instead.
func (IngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

// GPS position of an edge node.
type GpsPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   // degrees, WGS84
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"` // degrees, WGS84
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsPosition) Reset() {
	*x = GpsPosition{}
	mi := &file_api_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsPosition) ProtoMessage() {}

func (x *GpsPosition) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsPosition.ProtoReflect.Descriptor instead.
func (*GpsPosition) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *GpsPosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GpsPosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// One sensor sample produced by an edge node.
type SensorReading struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing sequence number within the device stream.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Unix epoch, nanoseconds (edge clock).
	TimestampNanos int64        `protobuf:"varint,2,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
	TemperatureC   float64      `protobuf:"fixed64,3,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"` // degrees Celsius
	VoltageV       float64      `protobuf:"fixed64,4,opt,name=voltage_v,json=voltageV,proto3" json:"voltage_v,omitempty"`             // volts
	CurrentA       float64      `protobuf:"fixed64,5,opt,name=current_a,json=currentA,proto3" json:"current_a,omitempty"`             // amperes
	Position       *GpsPosition `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`                               // optional; absent for fixed nodes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_api_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *SensorReading) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SensorReading) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

func (x *SensorReading) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *SensorReading) GetVoltageV() float64 {
	if x != nil {
		return x.VoltageV
	}
	return 0
}

func (x *SensorReading) GetCurrentA() float64 {
	if x != nil {
		return x.CurrentA
	}
	return 0
}

func (x *SensorReading) GetPosition() *GpsPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

// Batch of readings from one device. This is the payload signed by the
// edge node: the signature in TelemetryIngestRequest covers the exact
// serialized bytes of this message.
type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Readings      []*SensorReading       `protobuf:"bytes,2,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_api_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryBatch) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryBatch) GetReadings() []*SensorReading {
	if x != nil {
		return x.Readings
	}
	return nil
}

// One signed telemetry event sent over the ingestion stream.
type TelemetryIngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registered identity of the sending edge node.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Serialized TelemetryBatch — the exact bytes covered by `signature`.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// ML-DSA signature (FIPS 204) over `payload`.
	Signature          []byte             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureAlgorithm SignatureAlgorithm `protobuf:"varint,4,opt,name=signature_algorithm,json=signatureAlgorithm,proto3,enum=quantumshield.v1.SignatureAlgorithm" json:"signature_algorithm,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TelemetryIngestRequest) Reset() {
	*x = TelemetryIngestRequest{}
	mi := &file_api_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryIngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryIngestRequest) ProtoMessage() {}

func (x *TelemetryIngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryIngestRequest.ProtoReflect.Descriptor instead.
func (*TelemetryIngestRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryIngestRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryIngestRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryIngestRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TelemetryIngestRequest) GetSignatureAlgorithm() SignatureAlgorithm {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED
}

// Per-event acknowledgement/result for the edge node.
type TelemetryIngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest accepted sequence number from this device's stream so far.
	AckedSequence uint64       `protobuf:"varint,1,opt,name=acked_sequence,json=ackedSequence,proto3" json:"acked_sequence,omitempty"`
	Status        IngestStatus `protobuf:"varint,2,opt,name=status,proto3,enum=quantumshield.v1.IngestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryIngestResponse) Reset() {
	*x = TelemetryIngestResponse{}
	mi := &file_api_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryIngestResponse) ProtoMessage() {}

func (x *TelemetryIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryIngestResponse.ProtoReflect.Descriptor instead.
func (*TelemetryIngestResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryIngestResponse) GetAckedSequence() uint64 {
	if x != nil {
		return x.AckedSequence
	}
	return 0
}

func (x *TelemetryIngestResponse) GetStatus() IngestStatus {
	if x != nil {
		return x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

// Registers a device identity and stores its ML-DSA public key.
type RegisterDeviceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SignatureAlgorithm SignatureAlgorithm     `protobuf:"varint,2,opt,name=signature_algorithm,json=signatureAlgorithm,proto3,enum=quantumshield.v1.SignatureAlgorithm" json:"signature_algorithm,omitempty"`
	PublicKey          []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // raw ML-DSA public key bytes
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                          // optional metadata
	Location           string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`                    // optional metadata
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_api_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetSignatureAlgorithm() SignatureAlgorithm {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED
}

func (x *RegisterDeviceRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterDeviceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterDeviceRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        DeviceStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=quantumshield.v1.DeviceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_api_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceResponse) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

// Looks up the registered PQC public key of a device.
type GetDeviceKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceKeyRequest) Reset() {
	*x = GetDeviceKeyRequest{}
	mi := &file_api_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceKeyRequest) ProtoMessage() {}

func (x *GetDeviceKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceKeyRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceKeyRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceKeyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SignatureAlgorithm SignatureAlgorithm     `protobuf:"varint,2,opt,name=signature_algorithm,json=signatureAlgorithm,proto3,enum=quantumshield.v1.SignatureAlgorithm" json:"signature_algorithm,omitempty"`
	PublicKey          []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status             DeviceStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=quantumshield.v1.DeviceStatus" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetDeviceKeyResponse) Reset() {
	*x = GetDeviceKeyResponse{}
	mi := &file_api_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceKeyResponse) ProtoMessage() {}

func (x *GetDeviceKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceKeyResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceKeyResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetDeviceKeyResponse) GetSignatureAlgorithm() SignatureAlgorithm {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED
}

func (x *GetDeviceKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetDeviceKeyResponse) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

// Reports the current lifecycle state of a device.
type CheckDeviceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDeviceStatusRequest) Reset() {
	*x = CheckDeviceStatusRequest{}
	mi := &file_api_v1_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeviceStatusRequest) ProtoMessage() {}

func (x *CheckDeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckDeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *CheckDeviceStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type CheckDeviceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        DeviceStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=quantumshield.v1.DeviceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDeviceStatusResponse) Reset() {
	*x = CheckDeviceStatusResponse{}
	mi := &file_api_v1_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDeviceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeviceStatusResponse) ProtoMessage() {}

func (x *CheckDeviceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeviceStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckDeviceStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *CheckDeviceStatusResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CheckDeviceStatusResponse) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

var File_api_v1_telemetry_proto protoreflect.FileDescriptor

const file_api_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/telemetry.proto\x12\x10quantumshield.v1\"G\n" +
	"\vGpsPosition\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\xee\x01\n" +
	"\rSensorReading\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12'\n" +
	"\x0ftimestamp_nanos\x18\x02 \x01(\x03R\x0etimestampNanos\x12#\n" +
	"\rtemperature_c\x18\x03 \x01(\x01R\ftemperatureC\x12\x1b\n" +
	"\tvoltage_v\x18\x04 \x01(\x01R\bvoltageV\x12\x1b\n" +
	"\tcurrent_a\x18\x05 \x01(\x01R\bcurrentA\x129\n" +
	"\bposition\x18\x06 \x01(\v2\x1d.quantumshield.v1.GpsPositionR\bposition\"j\n" +
	"\x0eTelemetryBatch\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12;\n" +
	"\breadings\x18\x02 \x03(\v2\x1f.quantumshield.v1.SensorReadingR\breadings\"\xc4\x01\n" +
	"\x16TelemetryIngestRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12U\n" +
	"\x13signature_algorithm\x18\x04 \x01(\x0e2$.quantumshield.v1.SignatureAlgorithmR\x12signatureAlgorithm\"x\n" +
	"\x17TelemetryIngestResponse\x12%\n" +
	"\x0eacked_sequence\x18\x01 \x01(\x04R\rackedSequence\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.quantumshield.v1.IngestStatusR\x06status\"\xdc\x01\n" +
	"\x15RegisterDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12U\n" +
	"\x13signature_algorithm\x18\x02 \x01(\x0e2$.quantumshield.v1.SignatureAlgorithmR\x12signatureAlgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"m\n" +
	"\x16RegisterDeviceResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.quantumshield.v1.DeviceStatusR\x06status\"2\n" +
	"\x13GetDeviceKeyRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xe1\x01\n" +
	"\x14GetDeviceKeyResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12U\n" +
	"\x13signature_algorithm\x18\x02 \x01(\x0e2$.quantumshield.v1.SignatureAlgorithmR\x12signatureAlgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.quantumshield.v1.DeviceStatusR\x06status\"7\n" +
	"\x18CheckDeviceStatusRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"p\n" +
	"\x19CheckDeviceStatusResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.quantumshield.v1.DeviceStatusR\x06status*f\n" +
	"\x12SignatureAlgorithm\x12#\n" +
	"\x1fSIGNATURE_ALGORITHM_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tML_DSA_44\x10\x01\x12\r\n" +
	"\tML_DSA_65\x10\x02\x12\r\n" +
	"\tML_DSA_87\x10\x03*\x7f\n" +
	"\fDeviceStatus\x12\x1d\n" +
	"\x19DEVICE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEVICE_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17DEVICE_STATUS_SUSPENDED\x10\x02\x12\x19\n" +
	"\x15DEVICE_STATUS_REVOKED\x10\x03*\xaf\x01\n" +
	"\fIngestStatus\x12\x1d\n" +
	"\x19INGEST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INGEST_STATUS_ACCEPTED\x10\x01\x12$\n" +
	" INGEST_STATUS_REJECTED_SIGNATURE\x10\x02\x12!\n" +
	"\x1dINGEST_STATUS_REJECTED_DEVICE\x10\x03\x12\x1b\n" +
	"\x17INGEST_STATUS_THROTTLED\x10\x042\x87\x01\n" +
	"\x19TelemetryIngestionService\x12j\n" +
	"\x0fStreamTelemetry\x12(.quantumshield.v1.TelemetryIngestRequest\x1a).quantumshield.v1.TelemetryIngestResponse(\x010\x012\xc5\x02\n" +
	"\x11DeviceAuthService\x12c\n" +
	"\x0eRegisterDevice\x12'.quantumshield.v1.RegisterDeviceRequest\x1a(.quantumshield.v1.RegisterDeviceResponse\x12]\n" +
	"\fGetDeviceKey\x12%.quantumshield.v1.GetDeviceKeyRequest\x1a&.quantumshield.v1.GetDeviceKeyResponse\x12l\n" +
	"\x11CheckDeviceStatus\x12*.quantumshield.v1.CheckDeviceStatusRequest\x1a+.quantumshield.v1.CheckDeviceStatusResponseB8Z6github.com/anythinglord/quantumshield-hub/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_telemetry_proto_rawDescOnce sync.Once
	file_api_v1_telemetry_proto_rawDescData []byte
)

func file_api_v1_telemetry_proto_rawDescGZIP() []byte {
	file_api_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_api_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_telemetry_proto_rawDesc), len(file_api_v1_telemetry_proto_rawDesc)))
	})
	return file_api_v1_telemetry_proto_rawDescData
}

var file_api_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_telemetry_proto_goTypes = []any{
	(SignatureAlgorithm)(0),           // 0: quantumshield.v1.SignatureAlgorithm
	(DeviceStatus)(0),                 // 1: quantumshield.v1.DeviceStatus
	(IngestStatus)(0),                 // 2: quantumshield.v1.IngestStatus
	(*GpsPosition)(nil),               // 3: quantumshield.v1.GpsPosition
	(*SensorReading)(nil),             // 4: quantumshield.v1.SensorReading
	(*TelemetryBatch)(nil),            // 5: quantumshield.v1.TelemetryBatch
	(*TelemetryIngestRequest)(nil),    // 6: quantumshield.v1.TelemetryIngestRequest
	(*TelemetryIngestResponse)(nil),   // 7: quantumshield.v1.TelemetryIngestResponse
	(*RegisterDeviceRequest)(nil),     // 8: quantumshield.v1.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),    // 9: quantumshield.v1.RegisterDeviceResponse
	(*GetDeviceKeyRequest)(nil),       // 10: quantumshield.v1.GetDeviceKeyRequest
	(*GetDeviceKeyResponse)(nil),      // 11: quantumshield.v1.GetDeviceKeyResponse
	(*CheckDeviceStatusRequest)(nil),  // 12: quantumshield.v1.CheckDeviceStatusRequest
	(*CheckDeviceStatusResponse)(nil), // 13: quantumshield.v1.CheckDeviceStatusResponse
}
var file_api_v1_telemetry_proto_depIdxs = []int32{
	3,  // 0: quantumshield.v1.SensorReading.position:type_name -> quantumshield.v1.GpsPosition
	4,  // 1: quantumshield.v1.TelemetryBatch.readings:type_name -> quantumshield.v1.SensorReading
	0,  // 2: quantumshield.v1.TelemetryIngestRequest.signature_algorithm:type_name -> quantumshield.v1.SignatureAlgorithm
	2,  // 3: quantumshield.v1.TelemetryIngestResponse.status:type_name -> quantumshield.v1.IngestStatus
	0,  // 4: quantumshield.v1.RegisterDeviceRequest.signature_algorithm:type_name -> quantumshield.v1.SignatureAlgorithm
	1,  // 5: quantumshield.v1.RegisterDeviceResponse.status:type_name -> quantumshield.v1.DeviceStatus
	0,  // 6: quantumshield.v1.GetDeviceKeyResponse.signature_algorithm:type_name -> quantumshield.v1.SignatureAlgorithm
	1,  // 7: quantumshield.v1.GetDeviceKeyResponse.status:type_name -> quantumshield.v1.DeviceStatus
	1,  // 8: quantumshield.v1.CheckDeviceStatusResponse.status:type_name -> quantumshield.v1.DeviceStatus
	6,  // 9: quantumshield.v1.TelemetryIngestionService.StreamTelemetry:input_type -> quantumshield.v1.TelemetryIngestRequest
	8,  // 10: quantumshield.v1.DeviceAuthService.RegisterDevice:input_type -> quantumshield.v1.RegisterDeviceRequest
	10, // 11: quantumshield.v1.DeviceAuthService.GetDeviceKey:input_type -> quantumshield.v1.GetDeviceKeyRequest
	12, // 12: quantumshield.v1.DeviceAuthService.CheckDeviceStatus:input_type -> quantumshield.v1.CheckDeviceStatusRequest
	7,  // 13: quantumshield.v1.TelemetryIngestionService.StreamTelemetry:output_type -> quantumshield.v1.TelemetryIngestResponse
	9,  // 14: quantumshield.v1.DeviceAuthService.RegisterDevice:output_type -> quantumshield.v1.RegisterDeviceResponse
	11, // 15: quantumshield.v1.DeviceAuthService.GetDeviceKey:output_type -> quantumshield.v1.GetDeviceKeyResponse
	13, // 16: quantumshield.v1.DeviceAuthService.CheckDeviceStatus:output_type -> quantumshield.v1.CheckDeviceStatusResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v1_telemetry_proto_init() }
func file_api_v1_telemetry_proto_init() {
	if File_api_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_telemetry_proto_rawDesc), len(file_api_v1_telemetry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_api_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_api_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_api_v1_telemetry_proto_msgTypes,
	}.Build()
	File_api_v1_telemetry_proto = out.File
	file_api_v1_telemetry_proto_goTypes = nil
	file_api_v1_telemetry_proto_depIdxs = nil
}
