// QuantumShield Hub — API contract (v1).
//
// gRPC services and message contracts for the QuantumShield telemetry
// control plane:
//
//   - TelemetryIngestionService: bidirectional streaming ingestion of
//     edge telemetry with per-payload ML-DSA (Dilithium, FIPS 204)
//     signatures.
//   - DeviceAuthService: device identity lifecycle, PQC public-key lookup
//     and status checks.
//
// Wire rules (AGENTS.md §3, gRPC & Protocol Buffers):
//   - Never renumber, reorder or change the type of an existing field.
//   - New functionality only appends new field numbers.
//
// Transport: hybrid PQC mTLS (TLS 1.3, X25519 + ML-KEM-768). Payloads are
// signed by the edge node with ML-DSA and verified by the Ingestion
// Service before acceptance.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: api/v1/telemetry.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryIngestionService_StreamTelemetry_FullMethodName = "/quantumshield.v1.TelemetryIngestionService/StreamTelemetry"
)

// TelemetryIngestionServiceClient is the client API for TelemetryIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bidirectional streaming ingestion of signed edge telemetry. The edge
// node sends TelemetryIngestRequest events; the Ingestion Service verifies
// the ML-DSA signature and reports per-event results in stream order.
type TelemetryIngestionServiceClient interface {
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryIngestRequest, TelemetryIngestResponse], error)
}

type telemetryIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryIngestionServiceClient(cc grpc.ClientConnInterface) TelemetryIngestionServiceClient {
	return &telemetryIngestionServiceClient{cc}
}

func (c *telemetryIngestionServiceClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryIngestRequest, TelemetryIngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryIngestionService_ServiceDesc.Streams[0], TelemetryIngestionService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryIngestRequest, TelemetryIngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryIngestionService_StreamTelemetryClient = grpc.BidiStreamingClient[TelemetryIngestRequest, TelemetryIngestResponse]

// TelemetryIngestionServiceServer is the server API for TelemetryIngestionService service.
// All implementations must embed UnimplementedTelemetryIngestionServiceServer
// for forward compatibility.
//
// Bidirectional streaming ingestion of signed edge telemetry. The edge
// node sends TelemetryIngestRequest events; the Ingestion Service verifies
// the ML-DSA signature and reports per-event results in stream order.
type TelemetryIngestionServiceServer interface {
	StreamTelemetry(grpc.BidiStreamingServer[TelemetryIngestRequest, TelemetryIngestResponse]) error
	mustEmbedUnimplementedTelemetryIngestionServiceServer()
}

// UnimplementedTelemetryIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryIngestionServiceServer struct{}

func (UnimplementedTelemetryIngestionServiceServer) StreamTelemetry(grpc.BidiStreamingServer[TelemetryIngestRequest, TelemetryIngestResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedTelemetryIngestionServiceServer) mustEmbedUnimplementedTelemetryIngestionServiceServer() {
}
func (UnimplementedTelemetryIngestionServiceServer) testEmbeddedByValue() {}

// UnsafeTelemetryIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryIngestionServiceServer will
// result in compilation errors.
type UnsafeTelemetryIngestionServiceServer interface {
	mustEmbedUnimplementedTelemetryIngestionServiceServer()
}

func RegisterTelemetryIngestionServiceServer(s grpc.ServiceRegistrar, srv TelemetryIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryIngestionService_ServiceDesc, srv)
}

func _TelemetryIngestionService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryIngestionServiceServer).StreamTelemetry(&grpc.GenericServerStream[TelemetryIngestRequest, TelemetryIngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryIngestionService_StreamTelemetryServer = grpc.BidiStreamingServer[TelemetryIngestRequest, TelemetryIngestResponse]

// TelemetryIngestionService_ServiceDesc is the grpc.ServiceDesc for TelemetryIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quantumshield.v1.TelemetryIngestionService",
	HandlerType: (*TelemetryIngestionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _TelemetryIngestionService_StreamTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/telemetry.proto",
}

const (
	DeviceAuthService_RegisterDevice_FullMethodName    = "/quantumshield.v1.DeviceAuthService/RegisterDevice"
	DeviceAuthService_GetDeviceKey_FullMethodName      = "/quantumshield.v1.DeviceAuthService/GetDeviceKey"
	DeviceAuthService_CheckDeviceStatus_FullMethodName = "/quantumshield.v1.DeviceAuthService/CheckDeviceStatus"
)

// DeviceAuthServiceClient is the client API for DeviceAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Device identity lifecycle: registration, PQC key lookup and status
// checks. Used by the Ingestion Service for key retrieval and by
// provisioning tooling for registration.
type DeviceAuthServiceClient interface {
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	GetDeviceKey(ctx context.Context, in *GetDeviceKeyRequest, opts ...grpc.CallOption) (*GetDeviceKeyResponse, error)
	CheckDeviceStatus(ctx context.Context, in *CheckDeviceStatusRequest, opts ...grpc.CallOption) (*CheckDeviceStatusResponse, error)
}

type deviceAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceAuthServiceClient(cc grpc.ClientConnInterface) DeviceAuthServiceClient {
	return &deviceAuthServiceClient{cc}
}

func (c *deviceAuthServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAuthService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAuthServiceClient) GetDeviceKey(ctx context.Context, in *GetDeviceKeyRequest, opts ...grpc.CallOption) (*GetDeviceKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceKeyResponse)
	err := c.cc.Invoke(ctx, DeviceAuthService_GetDeviceKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAuthServiceClient) CheckDeviceStatus(ctx context.Context, in *CheckDeviceStatusRequest, opts ...grpc.CallOption) (*CheckDeviceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckDeviceStatusResponse)
	err := c.cc.Invoke(ctx, DeviceAuthService_CheckDeviceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceAuthServiceServer is the server API for DeviceAuthService service.
// All implementations must embed UnimplementedDeviceAuthServiceServer
// for forward compatibility.
//
// Device identity lifecycle: registration, PQC key lookup and status
// checks. Used by the Ingestion Service for key retrieval and by
// provisioning tooling for registration.
type DeviceAuthServiceServer interface {
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	GetDeviceKey(context.Context, *GetDeviceKeyRequest) (*GetDeviceKeyResponse, error)
	CheckDeviceStatus(context.Context, *CheckDeviceStatusRequest) (*CheckDeviceStatusResponse, error)
	mustEmbedUnimplementedDeviceAuthServiceServer()
}

// UnimplementedDeviceAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceAuthServiceServer struct{}

func (UnimplementedDeviceAuthServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedDeviceAuthServiceServer) GetDeviceKey(context.Context, *GetDeviceKeyRequest) (*GetDeviceKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceKey not implemented")
}
func (UnimplementedDeviceAuthServiceServer) CheckDeviceStatus(context.Context, *CheckDeviceStatusRequest) (*CheckDeviceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDeviceStatus not implemented")
}
func (UnimplementedDeviceAuthServiceServer) mustEmbedUnimplementedDeviceAuthServiceServer() {}
func (UnimplementedDeviceAuthServiceServer) testEmbeddedByValue()                           {}

// UnsafeDeviceAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceAuthServiceServer will
// result in compilation errors.
type UnsafeDeviceAuthServiceServer interface {
	mustEmbedUnimplementedDeviceAuthServiceServer()
}

func RegisterDeviceAuthServiceServer(s grpc.ServiceRegistrar, srv DeviceAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceAuthService_ServiceDesc, srv)
}

func _DeviceAuthService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAuthServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAuthService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAuthServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAuthService_GetDeviceKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAuthServiceServer).GetDeviceKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAuthService_GetDeviceKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAuthServiceServer).GetDeviceKey(ctx, req.(*GetDeviceKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAuthService_CheckDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAuthServiceServer).CheckDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAuthService_CheckDeviceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAuthServiceServer).CheckDeviceStatus(ctx, req.(*CheckDeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceAuthService_ServiceDesc is the grpc.ServiceDesc for DeviceAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quantumshield.v1.DeviceAuthService",
	HandlerType: (*DeviceAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _DeviceAuthService_RegisterDevice_Handler,
		},
		{
			MethodName: "GetDeviceKey",
			Handler:    _DeviceAuthService_GetDeviceKey_Handler,
		},
		{
			MethodName: "CheckDeviceStatus",
			Handler:    _DeviceAuthService_CheckDeviceStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/telemetry.proto",
}
